name: "🐛 Bug Report"
description: "Signaler un bug ou un comportement inattendu"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de remplir ce formulaire pour nous aider à reproduire le problème.

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      placeholder: Décrivez clairement le problème rencontré
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour reproduire
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Composant concerné
      options:
        - Frontend (React)
        - Backend (Spring Boot)
        - Base de données (MySQL)
        - Docker / Docker Compose
        - CI/CD (GitHub Actions)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack trace
      render: shell
