name: "✨ Feature Request"
description: "Proposer une nouvelle fonctionnalité"
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      placeholder: Quel problème cette fonctionnalité résout-elle ?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Composant concerné
      options:
        - Frontend (React)
        - Backend (Spring Boot)
        - Base de données
        - Docker / Infrastructure
        - CI/CD
        - Autre
